version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "X_topic:1:1"
  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - mongodb
      - kafka
  consumer1:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka
  consumer2:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka
  consumer3:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka
